### ISSUE TITLE
【注释错误】函数实际获取为当前限免游戏内容

### ISSUE THREAD

**Issue by ghost** [monsterxcn/nonebot_plugin_epicfree#10]
### 错误位置
- 目录： nonebot_plugin_epicfree
- 文件： data_source.py
- 行： 第65行

### 原内容
- 获取所有 Epic Game Store 促销游戏

### 修改内容
- 获取 Epic Game Store 当前限免及即将限免游戏

**Comment by monsterxcn** [comment]
感谢指出💦💦 不过我认为该注释的修改并不是十分必要，尽管可能不够准确。

使用 `获取所有 Epic Game Store 促销游戏` 作为注释主要基于下面两点考虑：

1. 函数 `query_epic_api()` 返回的结果并不仅限于当前限免、即将限免，有些长期免费的游戏或者其他游戏也可能会包含在返回中。根据接口路由 `freeGamesPromotions` 直译过来应该是 **免费游戏促销**，写注释的时候根据我的个人习惯做了点调整。
2. 相对于函数 `get_epic_free()` 从 `query_epic_api()` 的返回中筛选特定游戏的行为来说，`query_epic_api()` 的作用就是 **获取所有**。
