### ISSUE TITLE
私聊订阅功能用不上，应该改成机器人主人在群里发订阅就订阅那个群

### ISSUE THREAD

**Issue by 360add** [monsterxcn/nonebot_plugin_epicfree#13]
现在这样我机器人主人不是管理都弄不了订阅

**Comment by monsterxcn** [comment]
不是管理员你往群里订阅，别人都没意见吗？

要都没意见，你和管理员说一下让他发一句「喜加一订阅」也不是很难吧

**Comment by 360add** [comment]
开个定时发送谁会有意见，我开个60s新闻也没见有人来说意见啊，你找管理发谁来给你发

**Comment by monsterxcn** [comment]
不好意思，我是群主

**Comment by 360add** [comment]
反正是随便玩玩的功能，我就提一个，这功能应该掌握在超级用户手里，反正就是提一下，不加也无所谓

**Comment by 360add** [comment]
感谢大佬，还以为你不会改呢，给你点赞
![OYRFFJ4U9L _S%O)4ZAG2(R](https://github.com/monsterxcn/nonebot_plugin_epicfree/assets/140232510/4cdaa745-1dfa-4cc3-a17d-276d35edba70)
