### ISSUE TITLE
是否考虑加入定时推送？

### ISSUE THREAD

**Issue by SK-415** [monsterxcn/nonebot_plugin_epicfree#2]
可以发送类似 `喜加一订阅` 在当前私聊或群聊订阅。

之后按照每日或每周的频率定时爬取，如果有新的免费游戏就推送给所有订阅用户。

相关参考：[NoneBot2 定时任务](https://v2.nonebot.dev/advanced/scheduler.html)，[NoneBot2 本地存储插件](https://github.com/nonebot/plugin-localstore)。

PS：这只是我个人需求，如果觉得没必要就请 Close 吧。

**Comment by monsterxcn** [comment]
~~可以，什么时间有空来整一下（最近主要在做原神的 bot~~ 哇，是大佬（

定时任务这个会做，但是关于私聊订阅我还没有好的思路，我打算直接每周爬一次发送群消息

**Comment by SK-415** [comment]
我觉得私聊和群聊订阅没有太大区别。

假设不考虑边缘情况（已经订阅的群聊被踢出/私聊被删好友等），同时这个插件功能单一，没有其他需要额外储存的配置项。

那么订阅要记录的就两个参数：QQ 号、类型（群聊、私聊）。

使用一个简单的 Json 就可以储存，比如：

```json
{
  "private": [12345, 56789],
  "group": [114514, 1919810]
 }
```

之后推送只要分别轮询群聊和私聊的两组号码逐个发送即可。

配置文件不知道放哪也可以交给上面提到的 `本地储存插件` 来规划。

**Comment by monsterxcn** [comment]
(坏了，`git commit --amend` 遮不住这里的记录，打扰到你请见谅..

已经添加了订阅功能，欢迎体验！
