### ISSUE TITLE
请问群聊默认订阅是每次推送都会给所有群推送吗？

### ISSUE THREAD

**Issue by Bearlele** [monsterxcn/nonebot_plugin_epicfree#3]
请问群聊默认订阅是每次推送都会给所有群推送吗？可不可以限制群聊什么的_(:з」∠)_

**Comment by monsterxcn** [comment]
https://github.com/monsterxcn/nonebot_plugin_epicfree/blob/5086cd043e486485bd9705e776965c397a4aa45f/nonebot_plugin_epicfree/__init__.py#L39

你是指这里写的⌈默认启用群聊订阅⌋吗？当然是你在哪个群里发指令订阅以后就在哪个群发送消息提醒啊。

安装完插件后，如果从未在某个群聊中发送过订阅指令，那么插件是不会向任何群聊主动发送消息提醒的。
