### ISSUE TITLE
使用限免游戏资讯查询时报错

### ISSUE THREAD

**Issue by HuParry** [monsterxcn/nonebot_plugin_epicfree#5]
如图，在群聊中查询游戏资讯时，发生了报错，但是机器人还是正常地把资讯给发了出来。请问这个问题该怎么解决呢？

**Comment by HuParry** [comment]
>
![QQ图片20220423184323](https://user-images.githubusercontent.com/103566602/164891276-f822b28d-8b80-41f6-b876-d337cc946226.png)

**Comment by monsterxcn** [comment]
欸，没注意过。是因为遍历免费游戏列表的时候有的游戏没有商城链接。

感觉可以在这里再加一个 `AttributeError` 直接屏蔽掉？

https://github.com/monsterxcn/nonebot_plugin_epicfree/blob/68d23a0dedf5ee583ded632b8258220449d2b284/nonebot_plugin_epicfree/data_source.py#L116-L117

**Comment by Qiuyebai-1226** [comment]
目前依然会出现上述报错，情况与题主一致
