### ISSUE TITLE
【功能需求】退订功能

### ISSUE THREAD

**Issue by Ikaros-521** [monsterxcn/nonebot_plugin_epicfree#8]
我看了看说明和源码 ，是不是没有实现退订功能，这很尴尬

**Comment by monsterxcn** [comment]
呀，又鸽了一天（

在做了在做了，写订阅功能的时候没想那么多，就简单搞了搞，话说这么久了才有人提醒我 🤣

**Comment by Ikaros-521** [comment]
> 

www 说明用的人不够多，有待推广www
